### ISSUE TITLE
Annotation mean

### ISSUE THREAD

**Issue by Aiden-0209** [shengyuhao/DIVOTrack#10]
I have two questions about labels in a dataset.

**1. I don't know what the values for each file's label mean.**
DIVOTrack/datasets/DIVO/images/test/Shop_View1/det/det.txt 
Here's what's written in the file above.
1,-1,414.0,37.0,92.0,211.0,0.94

and then 
DIVOTrack/datasets/DIVO/labels_with_ids/test/Shop_View1/img1/Shop_View1_000001.txt
Here's what's written in the file above.
0 231 0.592448 0.474537 0.057813 0.245370

I thought it was information about the frame, person id, and bounding box. 
But this doesn't seem to be accurate, so I'm asking.

**2. Isn't the reason the folder names are separated for cross-view in the test set?**

DIVOTrack/datasets/DIVO/labels_with_ids_cross_view/train
DIVOTrack/datasets/DIVO/labels_with_ids_cross/test

**Comment by shengyuhao** [comment]
For Q1, "0 231 0.592448 0.474537 0.057813 0.245370" is `frame id, person id, box_center_x/image width, box_center_y/image height, box width/image width, and box height/image width`. (In the detection file, all person IDs are uniformly set to -1)

**Comment by shengyuhao** [comment]
For Q2, In "labels_with_ids_cross_view", starting IDs for different scenes are reset to 1, while "labels_with_ids_cross" has cumulative IDs, where the next scene starts from the previous scene's max ID+1. We will update them later.

**Comment by Aiden-0209** [comment]
Thank you for your answer :)
