### ISSUE TITLE
damaged model file

### ISSUE THREAD

**Issue by jellyshuang** [shengyuhao/DIVOTrack#16]
The error below appears when I'm running track.py.  The pickle files (model_last.zip) in hugging face seems damaged.

_pickle.UnpicklingError: invalid load key, '\xef'.

**Comment by shengyuhao** [comment]
Could you provide more details about which method you have used?

**Comment by jellyshuang** [comment]
I run the command:  python track.py mot --load_model DIVOTrack/CrossMOT/models/model_last.pth --test_divo --conf_thres 0.5 --reid_dim 512 --exp_name DIVOTrack

**Comment by jellyshuang** [comment]
I run this command:  python track.py mot  --test_divo --conf_thres 0.5 --reid_dim 512 --exp_name DIVOTrack

**Comment by shengyuhao** [comment]
Hi, I have run the code with the command: ```python track.py mot --load_model ../models/model_last.pth --test_divo --conf_thres 0.5 --reid_dim 512 --exp_name DIVOTrack``` without any errors. Is there something you have changed in the code?

**Comment by jellyshuang** [comment]
I haven't changed the code. 
<img width="1197" alt="image" src="https://github.com/shengyuhao/DIVOTrack/assets/46832527/fba8f108-6455-42bb-8235-ef0398a756ff">

**Comment by shengyuhao** [comment]
There are some possible solutions for you:

1. Re-download the [weights](https://huggingface.co/datasets/syhao777/DIVOTrack/resolve/main/CrossMOT/model_last.zip) and the CrossMOT code, make sure you have the right environment.
2. Re-train the model for several epochs and test them, checking for any problems with the ``` torch.load()``` or other functions.

I hope this can be helpful.

**Comment by jellyshuang** [comment]
I have tried the 1st solution, but the error stays the same.  Did you run the code (track.py) using the model in the hugging face website?

**Comment by shengyuhao** [comment]
yes, here is my screenshot
![image](https://github.com/shengyuhao/DIVOTrack/assets/45036892/65a380f0-7735-4b8f-b3ce-4705ff68bf23)
