### ISSUE TITLE
I can't get the CVIDF1 and CVMA indicators.

### ISSUE THREAD

**Issue by wwppnn** [shengyuhao/DIVOTrack#21]
Hello author, thank you and your team for the outstanding contribution. I encountered an issue while reproducing DIVOTrack, which is that I cannot obtain the CVIDF1 and CVMA metrics through the evaluation code. All the results obtained after running the evaluation code are related metrics for single-object tracking such as MOTA and IDF1. I have searched through the code you provided using keywords but did not find any relevant code for evaluating CVIDF1 and CVMA metrics. Do you know what could be the issue? Thank you very much for your assistance. In the README, you mentioned that these two metrics are obtained in MOTChallengeEvalKit_cv_test, but I couldn’t find the related code. In the code snippet below, CVMA metric is mentioned, but it seems that the two places indicated by the red arrows are saving the same metric, so I am still unable to obtain the aforementioned metrics. Do you know how to resolve this? Thank you
![M~{ROQIB$51B1 A0GYZ)1IC](https://github.com/shengyuhao/DIVOTrack/assets/78721779/a4a9ed30-3986-470d-9961-226584d4df8e)
.

**Comment by Hank0626** [comment]
Please refer to this file https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt

**Comment by chen-si-jia** [comment]
> Please refer to this file https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt

Using command "python MOT/evalMOT.py", the result is as follows:

![image](https://github.com/shengyuhao/DIVOTrack/assets/58644677/1d4fbc87-2ae5-442c-a3ea-49dd4f50d993)

CVIDF1 and CVMA indicators are not included in the result.

How to get CVIDF1 and CVMA indicators?

**Comment by Hank0626** [comment]
As shown in https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt
```
2. evaluate CVIDF1

MOT/evalMOT.py:

	gt_dir = "data/eval/wildscene_eval_cvma/gt"
	res_dir = "data/eval/wildscene_eval_cvma/track"
	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"

python MOT/evalMOT.py

3. evaluate CVMA

MOT/evalMOT.py:

	gt_dir = "data/eval/wildscene_eval_cvma/gt_cvma"
	res_dir = "data/eval/wildscene_eval_cvma/track_cvma"
	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"

python MOT/evalMOT.py
```

1. When you want to evaluate `CVIDF1`, change the file `MOT/evalMOT.py` to:
    ```python
	    gt_dir = "data/eval/{real_scene}_cvma/gt"
	    res_dir = "data/eval/{real_scene}_cvma/track"
	    seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
    ```
    The `IDF1` column of the resulting table is the value of CVIDF1.

2. When you want to evaluate `CVMA`, change the file `MOT/evalMOT.py` to:
    ```python
	    gt_dir = "data/eval/{real_scene}_cvma/gt_cvma"
	    res_dir = "data/eval/{real_scene}_cvma/track_cvma"
	    seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
    ```
    The `MOTA` column of the resulting table is the value of CVMA.

**Comment by Hank0626** [comment]
> > Please refer to this file https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt
> 
> Using command "python MOT/evalMOT.py", the result is as follows:
> 
> ![image](https://private-user-images.githubusercontent.com/58644677/309203196-1d4fbc87-2ae5-442c-a3ea-49dd4f50d993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTAxMzgsIm5iZiI6MTcwOTQ0OTgzOCwicGF0aCI6Ii81ODY0NDY3Ny8zMDkyMDMxOTYtMWQ0ZmJjODctMmFlNS00NDJjLWEzZWEtNDlkZDRmNTBkOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA3MTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzJjZDJiNDFmODJjNmI5N2YyMzBmMTBiNGVmNjYxNWY3MTQ2MDU1ZmYyNDJhNzFiNzQwNWYzNTMwYWY2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6V3583f4VlARedgGcYV0TbB8CeUddYFB9OFMzDe79Y)
> 
> CVIDF1 and CVMA indicators are not included in the result.
> 
> How to get CVIDF1 and CVMA indicators?

As shown in https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt
```
2. evaluate CVIDF1

MOT/evalMOT.py:

	gt_dir = "data/eval/wildscene_eval_cvma/gt"
	res_dir = "data/eval/wildscene_eval_cvma/track"
	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"

python MOT/evalMOT.py

3. evaluate CVMA

MOT/evalMOT.py:

	gt_dir = "data/eval/wildscene_eval_cvma/gt_cvma"
	res_dir = "data/eval/wildscene_eval_cvma/track_cvma"
	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"

python MOT/evalMOT.py
```

1. When you want to evaluate `CVIDF1`, change the file `MOT/evalMOT.py` to:
    ```python
	    gt_dir = "data/eval/{real_scene}_cvma/gt"
	    res_dir = "data/eval/{real_scene}_cvma/track"
	    seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
    ```
    Run `MOT/evalMOT.py`, and the `IDF1` column of the resulting table is the value of CVIDF1.

2. When you want to evaluate `CVMA`, change the file `MOT/evalMOT.py` to:
    ```python
	    gt_dir = "data/eval/{real_scene}_cvma/gt_cvma"
	    res_dir = "data/eval/{real_scene}_cvma/track_cvma"
	    seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
    ```
    Run `MOT/evalMOT.py`, and the `MOTA` column of the resulting table is the value of CVMA.

**Comment by chen-si-jia** [comment]
> > > Please refer to this file https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt
> > 
> > 
> > Using command "python MOT/evalMOT.py", the result is as follows:
> > ![image](https://private-user-images.githubusercontent.com/58644677/309203196-1d4fbc87-2ae5-442c-a3ea-49dd4f50d993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTAxMzgsIm5iZiI6MTcwOTQ0OTgzOCwicGF0aCI6Ii81ODY0NDY3Ny8zMDkyMDMxOTYtMWQ0ZmJjODctMmFlNS00NDJjLWEzZWEtNDlkZDRmNTBkOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA3MTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzJjZDJiNDFmODJjNmI5N2YyMzBmMTBiNGVmNjYxNWY3MTQ2MDU1ZmYyNDJhNzFiNzQwNWYzNTMwYWY2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6V3583f4VlARedgGcYV0TbB8CeUddYFB9OFMzDe79Y)
> > CVIDF1 and CVMA indicators are not included in the result.
> > How to get CVIDF1 and CVMA indicators?
> 
> As shown in https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt
> 
> ```
> 2. evaluate CVIDF1
> 
> MOT/evalMOT.py:
> 
> 	gt_dir = "data/eval/wildscene_eval_cvma/gt"
> 	res_dir = "data/eval/wildscene_eval_cvma/track"
> 	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"
> 
> python MOT/evalMOT.py
> 
> 3. evaluate CVMA
> 
> MOT/evalMOT.py:
> 
> 	gt_dir = "data/eval/wildscene_eval_cvma/gt_cvma"
> 	res_dir = "data/eval/wildscene_eval_cvma/track_cvma"
> 	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"
> 
> python MOT/evalMOT.py
> ```
> 
> 1. When you want to evaluate `CVIDF1`, change the file `MOT/evalMOT.py` to:
>    ```python
>        gt_dir = "data/eval/{real_scene}_cvma/gt"
>        res_dir = "data/eval/{real_scene}_cvma/track"
>        seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Run `MOT/evalMOT.py`, and the `IDF1` column of the resulting table is the value of CVIDF1.
> 2. When you want to evaluate `CVMA`, change the file `MOT/evalMOT.py` to:
>    ```python
>        gt_dir = "data/eval/{real_scene}_cvma/gt_cvma"
>        res_dir = "data/eval/{real_scene}_cvma/track_cvma"
>        seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
>    ```
>    
>    
>        
>          
>        
>    
>          
>        
>    
>        
>      
>    Run `MOT/evalMOT.py`, and the `MOTA` column of the resulting table is the value of CVMA.

Thank you!

**Comment by LPfly2000** [comment]
> > > > Please refer to this file [`main`/MOTChallengeEvalKit_cv_test/command.txt](https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt)
> > > 
> > > 
> > > Using command "python MOT/evalMOT.py", the result is as follows:
> > > ![image](https://private-user-images.githubusercontent.com/58644677/309203196-1d4fbc87-2ae5-442c-a3ea-49dd4f50d993.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk0NTAxMzgsIm5iZiI6MTcwOTQ0OTgzOCwicGF0aCI6Ii81ODY0NDY3Ny8zMDkyMDMxOTYtMWQ0ZmJjODctMmFlNS00NDJjLWEzZWEtNDlkZDRmNTBkOTkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzAzVDA3MTAzOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRlMzJjZDJiNDFmODJjNmI5N2YyMzBmMTBiNGVmNjYxNWY3MTQ2MDU1ZmYyNDJhNzFiNzQwNWYzNTMwYWY2M2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D6V3583f4VlARedgGcYV0TbB8CeUddYFB9OFMzDe79Y)
> > > CVIDF1 and CVMA indicators are not included in the result.
> > > How to get CVIDF1 and CVMA indicators?
> > 
> > 
> > As shown in [`main`/MOTChallengeEvalKit_cv_test/command.txt](https://github.com/shengyuhao/DIVOTrack/blob/main/MOTChallengeEvalKit_cv_test/command.txt)
> > ```
> > 2. evaluate CVIDF1
> > 
> > MOT/evalMOT.py:
> > 
> > 	gt_dir = "data/eval/wildscene_eval_cvma/gt"
> > 	res_dir = "data/eval/wildscene_eval_cvma/track"
> > 	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"
> > 
> > python MOT/evalMOT.py
> > 
> > 3. evaluate CVMA
> > 
> > MOT/evalMOT.py:
> > 
> > 	gt_dir = "data/eval/wildscene_eval_cvma/gt_cvma"
> > 	res_dir = "data/eval/wildscene_eval_cvma/track_cvma"
> > 	seq_file = "data/eval/wildscene_eval_cvma/seqs.txt"
> > 
> > python MOT/evalMOT.py
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 
> > 1. When you want to evaluate `CVIDF1`, change the file `MOT/evalMOT.py` to:
> >        gt_dir = "data/eval/{real_scene}_cvma/gt"
> >        res_dir = "data/eval/{real_scene}_cvma/track"
> >        seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    Run `MOT/evalMOT.py`, and the `IDF1` column of the resulting table is the value of CVIDF1.
> > 2. When you want to evaluate `CVMA`, change the file `MOT/evalMOT.py` to:
> >        gt_dir = "data/eval/{real_scene}_cvma/gt_cvma"
> >        res_dir = "data/eval/{real_scene}_cvma/track_cvma"
> >        seq_file = "data/eval/{real_scene}_cvma/seqs.txt"
> >        
> >          
> >        
> >    
> >          
> >        
> >    
> >        
> >      
> >    Run `MOT/evalMOT.py`, and the `MOTA` column of the resulting table is the value of CVMA.
> 
> Thank you!

Hi! I have download the dataset,but there are only five gt in test set.  Based on my understanding, this ground truth file is for single-view tracking labels, and there is no cross-view tracking label in the dataset's test set. How should I calculate CVAM and CVIDF1?do you know?thank you!
