### ISSUE TITLE
The size of figures in different views of train set is different. Is this normal?

### ISSUE THREAD

**Issue by chen-si-jia** [shengyuhao/DIVOTrack#22]
View 2 :
![image](https://github.com/shengyuhao/DIVOTrack/assets/58644677/dda7f5b2-5523-4f2f-ac4d-82a6dfe02f01)

View 1 and View 3:
![image](https://github.com/shengyuhao/DIVOTrack/assets/58644677/568d234e-04a9-4123-9162-78ea748a6a12)

**Comment by Hank0626** [comment]
Yes, the original image size is different for `View2`. You can resize it to match View1/View3.

**Comment by Hank0626** [comment]
By the way, our code has resized `View1` to `1920*1080` as well as the corresponding bounding box.

**Comment by chen-si-jia** [comment]
Thank you！



发自我的iPhone


------------------ Original ------------------
From: Peiyuan Liu ***@***.***&gt;
Date: Tue,Mar 5,2024 0:56 PM
To: shengyuhao/DIVOTrack ***@***.***&gt;
Cc: chen-si-jia ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [shengyuhao/DIVOTrack] The size of figures in different views oftrain set is different. Is this normal? (Issue #22)





 
Yes, the original image size is different for View2. You can resize it to match View1/View3.

**Comment by chen-si-jia** [comment]
Thank you!
