### ISSUE TITLE
Question about 'cross_view_feature' for multiview tracking

### ISSUE THREAD

**Issue by lunaryle** [shengyuhao/DIVOTrack#27]
Hi @shengyuhao, thank you for your great work, DIVOTrack.
While running the code `trackm.py` in the Multi_view_Tracking directory, I found the comment describing the input for the multiview tracking.
The comment says each line of .npy file is comprised of
`data: frame_id, view_id, xmin, ymin, w, h, score, 0, 0, 0, single_view_feature, cross_view_feature`.

1.  While I understand other values including `single_view_feature`, which would be the extracted feature of the bounding boxes while running `detect.py`, how do we get `cross_view_feature`, and what does it mean?

2. Why do you calculate cosine similarity with concatenated vector of single_view_feature and cross_view_feature, instead of just comparing feature between different views ? (at `gen_X()`)

I would really appreciate for your feedback.

**Comment by shengyuhao** [comment]
> Hi @shengyuhao, thank you for your great work, DIVOTrack. While running the code `trackm.py` in the Multi_view_Tracking directory, I found the comment describing the input for the multiview tracking. The comment says each line of .npy file is comprised of `data: frame_id, view_id, xmin, ymin, w, h, score, 0, 0, 0, single_view_feature, cross_view_feature`.
> 
> 1. While I understand other values including `single_view_feature`, which would be the extracted feature of the bounding boxes while running `detect.py`, how do we get `cross_view_feature`, and what does it mean?
> 2. Why do you calculate cosine similarity with concatenated vector of single_view_feature and cross_view_feature, instead of just comparing feature between different views ? (at `gen_X()`)
> 
> I would really appreciate for your feedback.

Hi, 
for Q1, ``detect.py`` is invalid. We extract the single-view and cross-view features for inference from [here](https://github.com/shengyuhao/DIVOTrack/tree/main/CrossMOT#tracking). CrossMOT has two branches for single and cross-view features; the details can be found in our paper.
for Q2, there are two similarity matrices for single-view and cross-view associations, this is one of CrossMOT's contributions to address the ID conflict issue for cross-view and single-view embeddings. The details can be found in Section 4.2 of our paper.

**Comment by lunaryle** [comment]
Thank you for your detailed answer.
