### ISSUE TITLE
Request dataset access

### ISSUE THREAD

**Issue by Aiden-0209** [shengyuhao/DIVOTrack#9]
hello
I admire your methods.
[shengyuhao@zju.edu.cn, gaoangwang@intl.zju.edu.cn]
I would like to access your dataset and have sent an email to the above mail.
Is it possible to check it out?

**Comment by shengyuhao** [comment]
Hi,Thanks for your interest! Please send me the license (https://github.com/shengyuhao/DIVOTrack/blob/main/LICENSE.md) in any format, and fill the blank. we will share the password of the dataset later.

**Comment by Aiden-0209** [comment]
Thank you for your answer.
I have replied to your email.
Thank you
